name = "cloudflare-docs-mcp"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[durable_objects]
bindings = [
  { name = "PRODUCT_SYNC_ACTOR", class_name = "ProductSyncActor" },
  { name = "CHAT_SESSION_ACTOR", class_name = "ChatSessionActor" },
]

[[d1_databases]]
binding = "DB"
database_name = "cloudflare-docs-best-practices"
database_id = "233820bc-7d62-46e1-b215-311479ae372f"
migrations_dir = "migrations"

[[migrations]]
tag = "v2_actors_refactor"
new_classes = ["ProductSyncActor", "ChatSessionActor"]

[vars]
AI_MODEL = "@cf/openai/gpt-oss-120b"

[observability]
enabled = true

[[durable_objects.bindings]]
name = "PRODUCT_SYNC_ACTOR"
class_name = "ProductSyncActor"

[[durable_objects.bindings]]
name = "CHAT_SESSION_ACTOR"
class_name = "ChatSessionActor"

[[migrations]]
tag = "v2"
new_classes = ["ProductSyncActor", "ChatSessionActor"]
