name = "cloudflare-docs-mcp"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[[d1_databases]]
binding = "DB"
database_name = "cloudflare-docs-best-practices"
database_id = "233820bc-7d62-46e1-b215-311479ae372f" # TODO: replace with actual database id

[vars]
AI_MODEL = "@cf/openai/gpt-oss-120b"

[observability]
enabled = true
