-- Migration: 0005_packet_refinement.sql
-- Created at: 2025-10-19 22:00:00
-- Description: Adds tables to support collaborative review of information packets.

-- Drop tables if they exist for clean migrations.
DROP TABLE IF EXISTS information_packets;
DROP TABLE IF EXISTS packet_highlights;

-- Table: information_packets
-- Description: Stores the structured content of a final "information packet" generated by an agent.
CREATE TABLE information_packets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL UNIQUE,
    -- Storing content as JSON allows for rich, structured rendering on the frontend.
    -- It could contain sections, code blocks, citations, etc.
    content TEXT NOT NULL, -- JSON object
    version INTEGER DEFAULT 1,
    created_at DATETIME DEFAULT (datetime('now')),
    FOREIGN KEY (job_id) REFERENCES feasibility_jobs (id)
);

-- Table: packet_highlights
-- Description: Stores highlighted sections and user comments for a specific packet,
-- enabling real-time collaboration and feedback.
CREATE TABLE packet_highlights (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    packet_id INTEGER NOT NULL,
    -- A unique identifier for the element/section within the packet's content.
    -- This could be a paragraph index, a block ID, etc.
    section_identifier TEXT NOT NULL,
    user_comment TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT (datetime('now')),
    FOREIGN KEY (packet_id) REFERENCES information_packets (id)
);

-- Update feasibility_jobs to link to the final packet
ALTER TABLE feasibility_jobs ADD COLUMN information_packet_id INTEGER;
